# CONFIG_I2C=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_CUSTOM_BH1750=y
# CONFIG_BH1750_CONTINUOUS_MODE=y
CONFIG_SPI=y
CONFIG_CUSTOM_RC522=y
CONFIG_MULTITHREADING=y
# CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_NO_OPTIMIZATIONS=y